### ISSUE TITLE
PyPI Name Transfer Request

### ISSUE THREAD

**Issue by tombulled** [davisp/namespace#1]
Hi @davisp,

You currently own the [`namespace`](https://pypi.org/project/namespace/) package name on PyPI for this project which was last released in 2009.

Please would you allow me to claim the package name for my [`namespace`](https://github.com/tombulled/namespace) library.

Kind regards,

@tombulled

**Comment by davisp** [comment]
More than willing. Let me know what needs doing. I assume something on PyPI directly?

**Comment by tombulled** [comment]
Awesome, thanks! I really appreciate that.

If you login to PyPI there should be an option to manage the `namespace` project. In the [project settings](https://pypi.org/manage/project/namespace/settings/) there should be an option to delete the project which will free up the `namespace` project name.

If you let me know once you've done this I will attempt to claim the project name and let you know that it is in safe hands.

**Comment by davisp** [comment]
Done and done. Its all yours!

**Comment by tombulled** [comment]
Thanks very much @davisp, the project name is in safe hands :pray: 
Have a good evening :slightly_smiling_face:
